GET https://ovs-backend.herokuapp.com/EC/ecs HTTP/1.1

###
POST https://ovs-backend.herokuapp.com/login HTTP/1.1
Content-Type: application/json

{
  "voterId" : "V88888",
  "password" : "Rgukt@123"
}

###

GET  https://ovs-backend.herokuapp.com/verified/V88888 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJWODg4ODgiLCJyb2xlIjoidm90ZXIiLCJpYXQiOjE2MjE4Mzk3MjgsImV4cCI6MTYyMTg0MTUyOH0.IELsvTF0CnVRKw6NLxgbSiwIxig_NZu95oNzJkKhI1U

###
GET https://ovs-backend.herokuapp.com/voters/V88888 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJWODg4ODgiLCJyb2xlIjoidm90ZXIiLCJpYXQiOjE2MjE3NTM2MzQsImV4cCI6MTYyMTc1NTQzNH0.K2QPd1-D_HTskS9K_7QLstDkOrRRyIl8Kupmc9WGP5U

###
GET https://ovs-backend.herokuapp.com/ec/verified/EC12345 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFQzEyMzQ1Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjIxNzgyMTA5LCJleHAiOjE2MjE3ODkzMDl9.Dt6QCuyO3uafY9wZ8dslVHEvcKsQw1IcLna5yMBHoTQ

###
GET https://ovs-backend.herokuapp.com/voters/V34566 HTTP/1.1


###
PATCH https://ovs-backend.herokuapp.com/voters HTTP/1.1

Content-Type: application/json

{
  "voterId" : "V22222",
  "mobile" : "1234567890",
}


###

GET https://ovs-backend.herokuapp.com/EC/Candidates/C22200 HTTP/1.1


###
GET https://ovs-backend.herokuapp.com/EC/requests/ HTTP/1.1

###
GET https://ovs-backend.herokuapp.com/EC/candidates HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFQzEyMzQ1Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjIxNTgwMDAyLCJleHAiOjE2MjE1ODE4MDJ9.5bllrsb95B_SgSqH1xT9vQo3MX1ikFyQs-Oww1Zc_JQ


###
GET https://ovs-backend.herokuapp.com/candidates/sarpanch/yemmiganur HTTP/1.1
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJWODg4ODgiLCJyb2xlIjoidm90ZXIiLCJpYXQiOjE2MjE3OTAyMzYsImV4cCI6MTYyMTc5MjAzNn0.lG6BUmpu3ZdkIaGpKAUL-pg3cj72-vVxyP7yZ-YsHhc

###
GET https://ovs-backend.herokuapp.com/candidates/mla/yemmiganur HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJWODg4ODgiLCJyb2xlIjoidm90ZXIiLCJpYXQiOjE2MjE2ODgxOTIsImV4cCI6MTYyMTY4OTk5Mn0.op5YZdLmNe3jKiu4YfHu4XortVJixQBRbIsUpXMzlo8

###
POST https://ovs-backend.herokuapp.com/cast-vote HTTP/1.1

Content-Type: application/json

{
  "voterId" : "V22000",
  "candidateId" : "C22000",
}

###
GET https://ovs-backend.herokuapp.com/ec/votes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFQzEyMzQ1Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjIxMzIzNzM3LCJleHAiOjE2MjEzMjU1Mzd9.RhpnXsQ1-PsyiybvSqO_EV-RUopuw2BzCvKbiNZaaUI

###
GET https://ovs-backend.herokuapp.com/ec/results/mla/yemmiganur HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFQzEyMzQ1Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjIxMzQ2MTEwLCJleHAiOjE2MjEzNDc5MTB9.sYPdRRi0DwLkDek55d9sjcl9oA7v9UYtZ8Cjresu3Xo
###
POST https://ovs-backend.herokuapp.com/ec/refresh-token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFQzEyMzQ1Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjIxMzQ4NTIyLCJleHAiOjE2MjEzNTAzMjJ9.1rC8C-C79D34spEBag8uw74NAzKAOKeosWeqwUu6us4


###
POST https://ovs-backend.herokuapp.com/ec/start-campaign HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFQzEyMzQ1Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjIyMDI4MzYzLCJleHAiOjE2MjIwMzAxNjN9.oODQqgKFv8gqWSSxScVGi4ARHJvI17g2v__Lr8v3Ib8

{
  "type":"mla",
  "district":"Khammam",
  "startDate":"2021-05-26T01:00:00.000Z",
  "endDate":"2021-05-27T01:00:00.000Z"
}

###
POST https://ovs-backend.herokuapp.com/ec/register HTTP/1.1
Content-Type: application/json

{
  "ecId" : "EC11111",
  "password" : "Rgukt123"
}

###
POST https://ovs-backend.herokuapp.com/register HTTP/1.1
Content-Type: application/json

{
  "voterId" : "V09090",
  "email" : "sami@sami.com",
  "firstName" : "sami",
  "lastName" : "Abdul",
  "password" : "Rgukt@123",
  "confirmPassword" : "Rgukt@123",
  "dob" : "2021-05-26T01:00:00.000Z",
  "gender" : "F",
  "mobile" : "1234567890",
  "state" : "Andhra Pradesh",
  "district" : "Kurnool",
  "constituency" : "yemmiganur",
  "mandal" : "yemmiganur",
  "village" :"yemmiganur",
}

###
POST https://ovs-backend.herokuapp.com/payment-order HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJWMDAwMDEiLCJyb2xlIjoidm90ZXIiLCJpYXQiOjE2MjIyMDc3MjUsImV4cCI6MTYyMjIwOTUyNX0.yk608aKuR717AZV0XnJ2FxiWGSc-e0XzlJrxb8aeBps

{
  "amount" : "10000",
  "currency" : "INR",
  "payment_capture" : "1"
}